// Mocks generated by Mockito 5.4.4 from annotations
// in ugaoo/test/pages/home_view/states/home_data_controllers/home_page_data_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ugaoo/pages/home_page/domain/entities/product_entities/product_data_entity.dart'
    as _i4;
import 'package:ugaoo/pages/home_page/domain/usecases/fetch_products_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FetchProductDataUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchProductDataUsecase extends _i1.Mock
    implements _i2.FetchProductDataUsecase {
  @override
  _i3.Future<_i4.ProductDataEntity?> fetchProducts() => (super.noSuchMethod(
        Invocation.method(
          #fetchProducts,
          [],
        ),
        returnValue: _i3.Future<_i4.ProductDataEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.ProductDataEntity?>.value(),
      ) as _i3.Future<_i4.ProductDataEntity?>);
}
