// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgpV7XG01sSVwizMHSBWfn2Xkgnu-IQ54',
    appId: '1:713109484916:web:f28f8d9e9e7071fce8a821',
    messagingSenderId: '713109484916',
    projectId: 'ugaoo-62cf9',
    authDomain: 'ugaoo-62cf9.firebaseapp.com',
    storageBucket: 'ugaoo-62cf9.appspot.com',
    measurementId: 'G-C003TCJ0M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SFsAM2gNh9bCeTEfcsWcyh8taus-Nuw',
    appId: '1:713109484916:android:086be37935acc66de8a821',
    messagingSenderId: '713109484916',
    projectId: 'ugaoo-62cf9',
    storageBucket: 'ugaoo-62cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOwFe8XNc2enI6g_OAe5eAL27UOAYEVj8',
    appId: '1:713109484916:ios:9571c66506989118e8a821',
    messagingSenderId: '713109484916',
    projectId: 'ugaoo-62cf9',
    storageBucket: 'ugaoo-62cf9.appspot.com',
    androidClientId: '713109484916-3l2a58e3k5eok93prtegpfmolf3qat96.apps.googleusercontent.com',
    iosClientId: '713109484916-2imthbtfbivh7jtco863pqikcdesgt28.apps.googleusercontent.com',
    iosBundleId: 'com.example.ugaoo',
  );
}
